name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Isometric Commit Calendar + Language Analysis
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size
          plugin_languages_indepth: true
          plugin_languages_analysis_timeout: 30
          plugin_languages_limit: 8
